name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
